version: "3"
services:
 emulator:
  image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
  ports:
   - 8554:8554
   - 5555:5555
  links:
   - server:server
  logging:
   driver: none
  devices:
   - /dev/kvm

 administrator:
  build: android_app
  links:
   - emulator:emulator

 server:
  build: server
  ports:
   - 12345:12345
